[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0", features = [] }

[dependencies]
anyhow = "1.0"
dirs = "4.0"
regex = "1.6"
serde_json = "1.0"
serde_rusqlite = { version = "0.30", features = [ ] }
serde = { version = "1.0", features = [ "derive" ] }
sha2 = { version = "0.10", features = [ ] }
chrono = { version = "0.4", features = [ "serde" ] }
rusqlite_migration = { version = "1.0", features = [ ] }
rusqlite = { version = ">= 0.27", features = [ "bundled-full", "functions", "serde_json" ] }
slugify = "0.1"

  [dependencies.tauri]
  version = "1.0"
  features = ["api-all"]

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
